# Generated by Django 5.1.1 on 2024-10-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('booking', '0001_initial'),
        ('kopero_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='available_time',
            field=models.ManyToManyField(to='booking.availabletime'),
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('PHOTOGRAPHER', 'photographer'), ('REGULAR', 'regular'), ('operations', 'Operations Admin')], default='Regular', help_text='Designates the role of the user in the system - For Authorization', max_length=20, verbose_name='user role'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('username', 'email'), name='unique_username_email'),
        ),
    ]
