# Generated by Django 5.1.1 on 2024-10-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kopero_auth', '0003_remove_profile_picture_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
