# Generated by Django 5.1.1 on 2024-10-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kopero_auth', '0003_user_picture'),
        ('kopero_auth', '0005_alter_user_picture'),
    ]

    operations = [
    ]
