# Generated by Django 5.1.1 on 2024-10-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('tag', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('rate_per_hour', models.FloatField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services')),
            ],
        ),
    ]
