# Generated by Django 5.1.1 on 2024-10-26 03:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('tag', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('rate_per_hour', models.FloatField(default=1000.0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services')),
            ],
        ),
    ]
