# Generated by Django 5.1.1 on 2024-10-17 17:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('booking', 'user')},
        ),
        migrations.RemoveField(
            model_name='review',
            name='average_rating',
        ),
    ]
