# Generated by Django 5.1.1 on 2024-10-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_availabletime_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='average_rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
